export const initalForm = {
    "id_piar": null,
    "est_piar": "",
    "id_est": null,
    "id_prof": null,
    "fec_dil": new Date().toISOString(),
    "nom_dil": "",
    "rol_se_ie": "",
    "nom_est": "",
    "ape_est": "",
    "lug_nac_est": "",
    "edad_est": 0,
    "fec_nac_est": new Date().toISOString(),
    "tip_doc_est": "",
    "otro_doc_est": "",
    "doc_est": "",
    "depa_est": [],
    "mun_est": [],
    "dir_est": "",
    "barrio_est": "",
    "tel_est": "",
    "ema_est": "",
    "cen_pro": false,
    "lugar_cen_pro": "",
    "grd_asp_est": "N/A",
    "grp_etn": "",
    "vic_conf": false,
    "reg_vic_conf": false,
    "afili_salud": false,
    "EPS": "",
    "contr_subsi": "",
    "lug_emer": "",
    "aten_salud": false,
    "frec_aten_salud": "N/A",
    "diag_med": false,
    "cual_diag_med": "",
    "ter_med": false,
    "cual_ter_med": [
      {
        "cual":'',
        "frec":'N/A'
      }
    ],
    "trat_med": false,
    "cual_trat_med": "",
    "cons_meds": false,
    "meds_frecuencia": [
      {
        "cual":'',
        "hor":'N/A'
      }
    ],
    "prods_mov": false,
    "cual_prods_mov": "",
    "nom_mam": "",
    "ocu_mam": "",
    "niv_ed_mam": "",
    "nom_pap": "",
    "ocu_pap": "",
    "niv_ed_pap": "",
    "nom_cui": "",
    "par_cui": "",
    "niv_ed_cui": "",
    "tel_cui": "",
    "ema_cui": "",
    "num_her": 0,
    "lug_ocu_est": "",
    "per_viv_est": "",
    "apo_cri_est": "",
    "baj_prot": false,
    "sub_inst_ent": false,
    "tip_sub": "",
    "vinc_otr_inst": false,
    "cual_inst": "",
    "no_inst": "",
    "ult_grad": "",
    "aprov_ult_grad": false,
    "obs_ult_grd": "",
    "infm_ped": false,
    "inst_infm": "",
    "prog_comp": false,
    "tipo_prog_comp": "",
    "nom_inst": "",
    "sed_inst": "",
    "trans_inst": "",
    "dist_inst": "",
    "nom_fir1_p1": "",
    "are_fir1_p1": "",
    "nom_fir2_p1": "",
    "are_fir2_p1": "",
    "nom_fir3_p1": "",
    "are_fir3_p1": "",
    "fec_dig_a2": new Date().toISOString(),
    "inst_edu_a2": "",
    "sed_a2": "",
    "jor_a2": "",
    "docs_ela": [
      {
        "nombres": "",
        "cargo": ""
      }
    ],
    "grd_est": "",
    "desc_1_est": "",
    "desc_2_est": "",
    

    "mats_ajts": [],
    "acc_fam": "",
    "estr_fam": "",
    "acc_doc": "",
    "estr_doc": "",
    "acc_dir": "",
    "estr_adm": "",
    "acc_adm": "",
    "estr_par": "",
    "acc_par": "",
    "nom_fir1_p2": "",
    "are_fir1_p2": "",
    "nom_fir2_p2": "",
    "are_fir2_p2": "",
    "nom_fir3_p3": "",
    "are_fir3_p2": ""
  }